name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # O 'master' si tu rama principal se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el repositorio
        uses: actions/checkout@v4

      # Va directo a desplegar lo que encuentre según el firebase.json
      - name: Desplegar en Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
